name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  set-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo '## File' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line; do
            echo $line >> $GITHUB_STEP_SUMMARY
          done < "sample.yaml"
          echo '```' >> $GITHUB_STEP_SUMMARY
