on:
  workflow_call:

env:
  A: ${{ vars.A }}

jobs:
  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo $A

  stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - run: echo $A
