on:
  workflow_call:

jobs:
  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo ${{ vars.A }}

  stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - run: echo ${{ vars.A }}
